/*
 * Static OpenAPI document of Push API resource
 *
 * Push API resources Open API documentation
 *
 * The version of the OpenAPI document: 0.3.15-sdk.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing State
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for State
        //private State instance;

        public StateTests()
        {
            // TODO uncomment below to create an instance of State
            //instance = new State();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of State
        /// </summary>
        [Fact]
        public void StateInstanceTest()
        {
            // TODO uncomment below to test "IsType" State
            //Assert.IsType<State>(instance);
        }
    }
}
